name: libcel
description: A Dart implementation of the Common Expression Language (CEL) using PetitParser
version: 1.0.2
homepage: https://github.com/libdbm/libcel
repository: https://github.com/libdbm/libcel
issue_tracker: https://github.com/libdbm/libcel/issues
documentation: https://pub.dev/documentation/libcel/latest/

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  petitparser: ^7.0.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
